export default {
    GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
    GET_PRODUCT_DETAILS: "GET_PRODUCT_DETAILS",
    CLEAR_PRODUCT_DETAILS: "CLEAR_PRODCUT_DETAILS",
    ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART"
};

